### ISSUE TITLE
From QueueMode.QueueModes to String

### ISSUE THREAD

**Issue by BilelBou** [Kelmatou/LeagueAPI#22]
Hello,

First of all thank you very much for this project.
I want to display the QueueMode into a Label, but i did not find out how to maybe force cast the QueueMode.QueueModes variable...

Maybe i'm not doing something great ?

Thanks and have a nice day :)

**Comment by Kelmatou** [comment]
Hi @BilelBou!

You're right, QueueModes are Long and there's no easy way at the moment to get a human readable name.
I'll extend QueueMode to get the String you need.

I noticed that some other Riot enums may need this conversion to String (like GameMode)
Thank you for your feedback, the update should come in the next days :)

**Comment by BilelBou** [comment]
Yes, for the moment we can do that : MyLabel.text = "\(QueueModes )"

**Comment by Kelmatou** [comment]
@BilelBou it will not always work, there could be missing spaced...
I'm creating release 4.1.0, most Riot enums will support CustomStringConvertible. It will let you write:
`print("\(QueueMode.QueueModes.RankedTeamFightTactics)" // Team Fight Tactics (Ranked)`

**Comment by BilelBou** [comment]
Ok nice, thank you 👍

**Comment by Kelmatou** [comment]
4.1.0 release for Carthage/CocoaPods or directly from Github, hope it will help you!

**Comment by BilelBou** [comment]
Hello, here for an update ? 

Thanks :D
And if you need some help i can help you :)

**Comment by Kelmatou** [comment]
Hello, I can but I didn't find any new QueueMode value. If you find one, I'd be happy to make an update
