### ISSUE TITLE
getRankedTier isn't working

### ISSUE THREAD

**Issue by r4ptus** [Kelmatou/LeagueAPI#8]
The function to get the Tier images isn't working anymore.
I tried the example from the wiki but only get the error wich tells me to create an issue

**Comment by Kelmatou** [comment]
Hi r4ptus!

Thank you for reporting this issue, I'm gonna take a look at that and will release a fix.
Just to confirm, you are talking about the getEmblem(for tier: RankedTier) method?

**Comment by r4ptus** [comment]
yes

**Comment by Kelmatou** [comment]
Should be fixed in v2.0.1
run `pod update` and you should be good :)
